[build]
  command = "npm run production"
  publish = "public"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[context.production.environment]
  ELEVENTY_ENV = "production" # excludes Forestry drafts from production build
