backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "src/img"
public_folder: "/img"


collections:
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Summary", name: "summary", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Date", name: "date", widget: "datetime"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        required: false
        summary: "{{fields.tag}}"
        field: {label: "Tag", name: "tag", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Alt Text", name: "alt", widget: "string"}
      - {label: "Image Caption", name: "caption", widget: "string"}
      - {label: "Post", name: "body", widget: "markdown"}
